"""Shared utilities for NocoDB schema export tools.

Provides functions to extract portable schemas from NocoDB API responses,
removing system fields and internal IDs to create reusable schema definitions.
"""

from typing import Any

# System field types that shouldn't be exported (auto-generated by NocoDB)
SYSTEM_FIELD_TYPES = {
    "CreatedTime",
    "LastModifiedTime",
    "CreatedBy",
    "LastModifiedBy",
}

# Internal keys to remove from field definitions
INTERNAL_KEYS = {
    "id",
    "fk_model_id",
    "base_id",
    "source_id",
    "table_id",
    "created_at",
    "updated_at",
    "order",
    "system",
}


def extract_portable_field(field: dict[str, Any]) -> dict[str, Any] | None:
    """Extract portable schema from a single field.

    Args:
        field: Field definition from NocoDB API response

    Returns:
        Cleaned field definition, or None if the field should be skipped
        (system field or auto-generated primary key)
    """
    field_type = field.get("uidt") or field.get("type")

    # Skip system fields
    if field_type in SYSTEM_FIELD_TYPES:
        return None

    # Skip primary key if it's auto-generated
    if field.get("pk") and field.get("ai"):
        return None

    # Create clean field definition
    clean_field = {}
    for key, value in field.items():
        if key not in INTERNAL_KEYS and value is not None:
            # Normalize type field name: uidt -> type
            if key == "uidt":
                clean_field["type"] = value
            else:
                clean_field[key] = value

    return clean_field


def extract_portable_table_schema(table_data: dict[str, Any]) -> dict[str, Any]:
    """Extract portable schema from table metadata.

    Removes system fields and internal IDs to create a reusable schema
    compatible with `nocodb tables create --fields`.

    Args:
        table_data: Table metadata from table_read_v3()

    Returns:
        Portable table schema with title and fields array
    """
    fields = table_data.get("fields", table_data.get("columns", []))
    portable_fields = []

    for field in fields:
        clean_field = extract_portable_field(field)
        if clean_field:
            portable_fields.append(clean_field)

    return {
        "title": table_data.get("title", "Untitled"),
        "fields": portable_fields,
    }


def extract_portable_base_schema(
    base_data: dict[str, Any],
    tables_data: list[dict[str, Any]],
) -> dict[str, Any]:
    """Extract portable schema from base metadata and all tables.

    Args:
        base_data: Base metadata from base_read()
        tables_data: List of table metadata from table_read_v3() for each table

    Returns:
        Portable base schema with embedded table schemas
    """
    portable_tables = []

    for table in tables_data:
        portable_table = extract_portable_table_schema(table)
        # Add table_name for reference (useful for recreating)
        if "table_name" in table:
            portable_table["table_name"] = table["table_name"]
        portable_tables.append(portable_table)

    schema = {
        "title": base_data.get("title", "Untitled"),
        "tables": portable_tables,
    }

    # Include description if present
    if base_data.get("description"):
        schema["description"] = base_data["description"]

    return schema
